// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID             pgtype.UUID
	Email          string
	Password       string
	GoogleClientID string
	FullName       string
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type Website struct {
	ID        string
	Domain    string
	Name      string
	UserID    pgtype.UUID
	ClientID  pgtype.Text
	Host      []string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
